theme: jekyll-theme-slate
title: Sexism detection in Russian forum and social network's messages.
description: The report of the GSOC'19 project

docs_list_title: ACME Documentation
docs:

- title: Introduction
  url: sources.md

- title: Configuration
  url: sources.md
